### ISSUE TITLE
The link of ItemInformation of Books after processing in README.md maybe wrong

### ISSUE THREAD

**Issue by Xiuchen519** [bytedance/HLLM#1]
Now, the link of ItemInformation of Books after processing is https://huggingface.co/ByteDance/HLLM/resolve/main/Interactions/amazon_books.csv. It is repetitive with [Interactions](https://huggingface.co/ByteDance/HLLM/resolve/main/Interactions/amazon_books.csv), maybe it should be changed to https://huggingface.co/ByteDance/HLLM/resolve/main/ItemInformation/amazon_books.csv

**Comment by ssyzeChen** [comment]
We are very sorry for the incorrect link. We have fixed this issue. Thank you for you help! 🙏
