### ISSUE TITLE
Questions about extracting fp32 consolidated weights from DeepSpeed checkpoints

### ISSUE THREAD

**Issue by rucliujn** [bytedance/HLLM#10]
Hi, 
I'm trying to reproduce the results and using the zero_to_fp32.py to extract the fp32 consolidated weights from DeepSpeed checkpoints.  However, it keeps reporting the following errors:
![image](https://github.com/user-attachments/assets/4a33ad4a-c660-41f1-b79f-ccce68dc1988)
Have you come across the same error before? And how do you extract the fp32 weights from deepspeed checkpoint?

Thank you!

**Comment by blueColdSea** [comment]
How did you solve it？I met the same problem.

**Comment by rucliujn** [comment]
I solved it by adding
```
import sys
sys.path.append('your-path/HLLM/code')
```
to the zero_to_fp32.py. (change `your-path` to the absolute path of your repository)

**Comment by blueColdSea** [comment]
Thanks for your help！It works.
