### ISSUE TITLE
NCCL error

### ISSUE THREAD

**Issue by walegahaha123** [bytedance/HLLM#12]
![fig](https://github.com/user-attachments/assets/80398e7f-975b-4de1-9c9b-ff85633a5d77)
code/overall/LLM_deepspeed.yaml, train_batch_size and eval_batch_size both set 1
NCCL error for single gpu, do you know why? 
thx！

**Comment by walegahaha123** [comment]
torchrun --nnodes 1 --node_rank 0 --master_addr localhost --master_port 12345 run.py --config_file overall/LLM_deepspeed.yaml HLLM/HLLM.yaml --MAX_ITEM_LIST_LENGTH 10 --epochs 5 --optim_args.learning_rate 1e-4 --MAX_TEXT_LENGTH 256 --train_batch_size 1 --gradient_checkpointing True --stage 3

this config has the same error
nvmlDeviceGetP2PStatus(0,0,NVML_P2P_CAPS_INDEX_READ) failed: Invalid Argument

**Comment by ssyzeChen** [comment]
Hi，I'm sorry that I haven't met this before. I just test on a single gpu machine, and it seems to be good for me.
