### ISSUE TITLE
torch.distributed.DistBackendError: [3] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout [rank3]: Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:570 (most recent call first):

### ISSUE THREAD

**Issue by cijiezheng** [bytedance/HLLM#20]
Has anyone encountered a similar problem? When I trained on my own dataset, it could train successfully when I used less data (about 20 million), but when I increased it to 250 million, problems started to occur.

[rank3]:[W1111 16:02:57.226522542 socket.cpp:428] [c10d] While waitForInput, poolFD failed with (errno: 0 - Success).
[rank3]: Traceback (most recent call last):
[rank3]:   File "/workspace/llm4rec/HLLM/code/run.py", line 147, in <module>
[rank3]:     run_loop(local_rank=local_rank, config_file=config_file, extra_args=extra_args)
[rank3]:   File "/workspace/llm4rec/HLLM/code/run.py", line 117, in run_loop
[rank3]:     best_valid_score, best_valid_result = trainer.fit(
[rank3]:   File "/workspace/llm4rec/HLLM/code/REC/trainer/trainer.py", line 346, in fit
[rank3]:     self.model, self.optimizer = self.lite.setup(self.model, self.optimizer)
[rank3]:   File "/usr/local/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 245, in setup
[rank3]:     module, optimizers = self._strategy.setup_module_and_optimizers(  # type: ignore[assignment]
[rank3]:   File "/usr/local/lib/python3.10/site-packages/lightning/fabric/strategies/deepspeed.py", line 331, in setup_module_and_optimizers
[rank3]:     self._deepspeed_engine, optimizer = self._initialize_engine(module, optimizers[0])
[rank3]:   File "/usr/local/lib/python3.10/site-packages/lightning/fabric/strategies/deepspeed.py", line 607, in _initialize_engine
[rank3]:     deepspeed_engine, deepspeed_optimizer, _, _ = deepspeed.initialize(
[rank3]:   File "/usr/local/lib/python3.10/site-packages/deepspeed/__init__.py", line 181, in initialize
[rank3]:     engine = DeepSpeedEngine(args=args,
[rank3]:   File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
[rank3]:     self._configure_distributed_model(model)
[rank3]:   File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1157, in _configure_distributed_model
[rank3]:     self._broadcast_model()
[rank3]:   File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1077, in _broadcast_model
[rank3]:     dist.broadcast(p.data, groups._get_broadcast_src_rank(), group=self.seq_data_parallel_group)
[rank3]:   File "/usr/local/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
[rank3]:     return func(*args, **kwargs)
[rank3]:   File "/usr/local/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
[rank3]:     return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[rank3]:   File "/usr/local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
[rank3]:     return fn(*args, **kwargs)
[rank3]:   File "/usr/local/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 199, in broadcast
[rank3]:     return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[rank3]:   File "/usr/local/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank3]:     return func(*args, **kwargs)
[rank3]:   File "/usr/local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2209, in broadcast
[rank3]:     work = group.broadcast([tensor], opts)
[rank3]: torch.distributed.DistBackendError: [3] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout
[rank3]: Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:570 (most recent call first):
[rank3]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fa71c962f86 in /usr/local/lib/python3.10/site-packages/torch/lib/libc10.so)
[rank3]: frame #1: <unknown function> + 0x16583cb (0x7fa75330e3cb in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #2: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x7fa7579c0b82 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #3: c10d::TCPStore::get(std::string const&) + 0xa1 (0x7fa7579c1d71 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #4: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fa7579767c1 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fa7579767c1 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fa7579767c1 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fa7579767c1 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fa7579767c1 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x7fa71dc5e8ff in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #10: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x114c (0x7fa71dc6a6dc in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #11: c10d::ProcessGroupNCCL::broadcast(std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::BroadcastOptions const&) + 0x643 (0x7fa71dc771c3 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #12: <unknown function> + 0x5cb44e6 (0x7fa75796a4e6 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #13: <unknown function> + 0x5cbf796 (0x7fa757975796 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #14: <unknown function> + 0x52dfa0b (0x7fa756f95a0b in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #15: <unknown function> + 0x52dd284 (0x7fa756f93284 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #16: <unknown function> + 0x1adf2b8 (0x7fa7537952b8 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #17: <unknown function> + 0x5cc46aa (0x7fa75797a6aa in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #18: <unknown function> + 0x5cd428c (0x7fa75798a28c in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #19: <unknown function> + 0xdb3265 (0x7fa76acc8265 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank3]: frame #20: <unknown function> + 0x4b00e4 (0x7fa76a3c50e4 in /usr/local/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank3]: frame #21: <unknown function> + 0x23ecc3 (0x5599787dbcc3 in /usr/local/bin/python3)
[rank3]: frame #22: _PyObject_MakeTpCall + 0x8c (0x559978614c4c in /usr/local/bin/python3)
[rank3]: frame #23: <unknown function> + 0x224782 (0x5599787c1782 in /usr/local/bin/python3)
[rank3]: frame #24: _PyEval_EvalFrameDefault + 0x8985 (0x5599786010a5 in /usr/local/bin/python3)
[rank3]: frame #25: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #26: PyVectorcall_Call + 0xc6 (0x5599786156c6 in /usr/local/bin/python3)
[rank3]: frame #27: _PyEval_EvalFrameDefault + 0x44c6 (0x5599785fcbe6 in /usr/local/bin/python3)
[rank3]: frame #28: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #29: _PyEval_EvalFrameDefault + 0x7d9a (0x5599786004ba in /usr/local/bin/python3)
[rank3]: frame #30: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #31: PyVectorcall_Call + 0xc6 (0x5599786156c6 in /usr/local/bin/python3)
[rank3]: frame #32: _PyEval_EvalFrameDefault + 0x44c6 (0x5599785fcbe6 in /usr/local/bin/python3)
[rank3]: frame #33: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #34: <unknown function> + 0x224748 (0x5599787c1748 in /usr/local/bin/python3)
[rank3]: frame #35: _PyEval_EvalFrameDefault + 0x7d9a (0x5599786004ba in /usr/local/bin/python3)
[rank3]: frame #36: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #37: PyVectorcall_Call + 0xc6 (0x5599786156c6 in /usr/local/bin/python3)
[rank3]: frame #38: _PyEval_EvalFrameDefault + 0x44c6 (0x5599785fcbe6 in /usr/local/bin/python3)
[rank3]: frame #39: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #40: _PyEval_EvalFrameDefault + 0x7d9a (0x5599786004ba in /usr/local/bin/python3)
[rank3]: frame #41: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #42: <unknown function> + 0x224748 (0x5599787c1748 in /usr/local/bin/python3)
[rank3]: frame #43: _PyEval_EvalFrameDefault + 0x8985 (0x5599786010a5 in /usr/local/bin/python3)
[rank3]: frame #44: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #45: <unknown function> + 0x224748 (0x5599787c1748 in /usr/local/bin/python3)
[rank3]: frame #46: _PyEval_EvalFrameDefault + 0x8985 (0x5599786010a5 in /usr/local/bin/python3)
[rank3]: frame #47: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #48: _PyObject_Call_Prepend + 0x1d9 (0x5599786161c9 in /usr/local/bin/python3)
[rank3]: frame #49: <unknown function> + 0xd59b3 (0x5599786729b3 in /usr/local/bin/python3)
[rank3]: frame #50: <unknown function> + 0xcbe37 (0x559978668e37 in /usr/local/bin/python3)
[rank3]: frame #51: _PyObject_MakeTpCall + 0x8c (0x559978614c4c in /usr/local/bin/python3)
[rank3]: frame #52: _PyEval_EvalFrameDefault + 0x84b6 (0x559978600bd6 in /usr/local/bin/python3)
[rank3]: frame #53: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #54: _PyEval_EvalFrameDefault + 0x7d9a (0x5599786004ba in /usr/local/bin/python3)
[rank3]: frame #55: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #56: _PyEval_EvalFrameDefault + 0x6f27 (0x5599785ff647 in /usr/local/bin/python3)
[rank3]: frame #57: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #58: _PyEval_EvalFrameDefault + 0x6f27 (0x5599785ff647 in /usr/local/bin/python3)
[rank3]: frame #59: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #60: _PyEval_EvalFrameDefault + 0x6f27 (0x5599785ff647 in /usr/local/bin/python3)
[rank3]: frame #61: <unknown function> + 0x131cd8 (0x5599786cecd8 in /usr/local/bin/python3)
[rank3]: frame #62: <unknown function> + 0x224748 (0x5599787c1748 in /usr/local/bin/python3)
[rank3]: . This may indicate a possible application crash on rank 0 or a network set up issue.
11 Nov 16:00    INFO  recipe_2024103111_720
The number of users: 21977840
Average actions of users: 11.596806674213965
The number of items: 60898
Average actions of items: 4185.3088001050955
The number of inters: 254872750
The sparsity of the dataset: 99.98095699998923%
^[[A11 Nov 16:03    INFO  HLLM(
  (item_llm): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (user_llm): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
)
Trainable parameters: 204536065.0
11 Nov 16:03    INFO  Use consine scheduler with 2817.0 warmup 28170 total steps
world_size: 4 local_world_size: 4
11 Nov 16:03    INFO  Use deepspeed strategy
You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
initializing deepspeed distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Enabling DeepSpeed BF16. Model parameters and inputs will be cast to `bfloat16`.
W1111 16:03:46.250000 140648530126016 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3965 closing signal SIGTERM
W1111 16:03:46.250000 140648530126016 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3966 closing signal SIGTERM
W1111 16:03:46.250000 140648530126016 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3967 closing signal SIGTERM
E1111 16:03:53.043000 140648530126016 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 3 (pid: 3968) of binary: /usr/local/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-11_16:03:46
  host      : hwbj4-bigdatagpu-10-16-16-139.meitu-inc.com
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3968)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
+ echo 'start_time: 2024-11-11T15:13:01'
start_time: 2024-11-11T15:13:01

**Comment by lixali** [comment]
I have the same error.

**Comment by ssyzeChen** [comment]
Sorry, we haven't met this before, maybe you could check if the issue is due to the construction of the trainset being too time-consuming, which might require re-implementing the dataset.
