### ISSUE TITLE
Questions about online model

### ISSUE THREAD

**Issue by badcode-iip** [bytedance/HLLM#21]
Hello, very inspiring work! But there is very little introduction about online models in the paper, and I have some questions that I hope to receive your reply.

1. As far as I know, the items of Douyin are mainly short videos. What's the input of Item LLM? The features related to video/image understanding, or only text descriptions?
2. Did some acceleration techniques similar to HSTU be used during training? For example, is the sample constructed by point?
3. Is the input of user LLM only the output of item LLM? How to use user side features and how to deal with new users?

**Comment by ssyzeChen** [comment]
Hi~
1. Text only now.
2. No, we don't use streaming training now.
3. Yes, but you could try to use other side infos to enhance the model.
