### ISSUE TITLE
Evaluation becomes very slow when inceasing negative nums

### ISSUE THREAD

**Issue by yjdy** [bytedance/HLLM#22]
I trained IDNet from scratch in Amazon books on my 8GPU machine. When I do not set  num_negatives, the training and evaluation is normal. 

When num_negatives is 512, training time of an epoch is 4 times than before, but the evaluation becomes very very slow. The evaluation time is longer than 8 hours. 

Could you please provides some suggetions to fix the problems? Thank you

Great job, by the way.

**Comment by ssyzeChen** [comment]
Hi~There should not be difference in evaluation when you set num_negatives or not especially on IDNet, maybe you could provide more information.
