### ISSUE TITLE
Can I resume run from checkpoint? My cluster has max run time of 48 hours and resuming from checkpoint is only option to finish

### ISSUE THREAD

**Issue by lixali** [bytedance/HLLM#23]
Is there a script to resume training from checkpoint? The weights are stored in "pt" files. Is the optimizer states saved somewhere? 

It will be very helpful if the code supports resuming from checkpoint.

**Comment by ssyzeChen** [comment]
Sorry, the pretrained weights only contain the model parameters, we do not save optimizers after training 😢. You could try to just load the weights and continue to finetune the model.

**Comment by threestone965** [comment]
https://github.com/bytedance/HLLM/issues/16#issuecomment-2466799582
