### ISSUE TITLE
how can you make bert (encoder-only )model into item-llm (decoder-only)

### ISSUE THREAD

**Issue by happywinder** [bytedance/HLLM#25]
In your paper **HLLM: Enhancing Sequential Recommendations via Hierarchical Large Language Models for Item and User Modeling**,I found you test bert-base,bert-large as item-llm in Table 5,but previous description reveal  item-llm is a decoder-only model,how can you make bert an encoder-only model into decoder-only, and test it's performance?

**Comment by ssyzeChen** [comment]
Hi~ We use traditional bert (uses bi-direction attention not casual attention) to extract item feature in our experiments.
