### ISSUE TITLE
dataloader collate_fn

### ISSUE THREAD

**Issue by Sammir-z** [bytedance/HLLM#27]
Problem description：

/gemini/code/HLLM-main/code/REC/data/dataset/collate_fn.py:43: UserWarning: An output with one or more elements was resized since it had shape [22], which does not match the required output shape [16, 11]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  return torch.stack(batch, 0, out=out)
for batch_idx, data in enumerate(train_data):/gemini/code/HLLM-main/code/REC/data/dataset/collate_fn.py:43: UserWarning: An output with one or more elements was resized since it had shape [22], which does not match the required output shape [16, 11]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  return torch.stack(batch, 0, out=out)
/gemini/code/HLLM-main/code/REC/data/dataset/collate_fn.py:43: UserWarning: An output with one or more elements was resized since it had shape [22], which does not match the required output shape [16, 11]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  return torch.stack(batch, 0, out=out)
/gemini/code/HLLM-main/code/REC/data/dataset/collate_fn.py:43: UserWarning: An output with one or more elements was resized since it had shape [22], which does not match the required output shape [16, 11]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  return torch.stack(batch, 0, out=out)
/gemini/code/HLLM-main/code/REC/data/dataset/collate_fn.py:43: UserWarning: An output with one or more elements was resized since it had shape [22], which does not match the required output shape [16, 11]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  return torch.stack(batch, 0, out=out)

  File "/root/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.11/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/gemini/code/HLLM-main/code/REC/data/dataset/collate_fn.py", line 134, in customize_rmpad_collate
    output[key] = customize_collate([d[key] for d in batch])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gemini/code/HLLM-main/code/REC/data/dataset/collate_fn.py", line 43, in customize_collate
    return torch.stack(batch, 0, out=out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to resize storage that is not resizable

How should I modify this issue？

**Comment by ssyzeChen** [comment]
Hi~ which dataset and model do you use? We haven't met this before

**Comment by Sammir-z** [comment]
> Hi~ which dataset and model do you use? We haven't met this before

I have also solved this problem. I used Llama 1B and it seems that the issue was with the PyTorch version. Then, I commented out part of the collate_fn and the problem was resolved.
