### ISSUE TITLE
BERT as Item Model 

### ISSUE THREAD

**Issue by JingyuanHe1222** [bytedance/HLLM#28]
Hi, I am looking at Table 5 of the paper and wonder if when BERT Is plugged in as the item model, is the user LLM the original SASRec or the SASRec-1B (replacing its network structure with TinyLlama-1.1B) as mentioned in the baseline section of the paper? 
If so, how do your coordinate between the difference in hidden dimensions of the two models when feeding the BERT embeddings into tinyllama? 

Thanks in advance!

**Comment by ssyzeChen** [comment]
Hi~ we use a linear projector to solve the problem with different hidden dims.
