### ISSUE TITLE
咨询一下，模型训练后模型是否有保存pytorch_model.bin，或者如何转换呢

### ISSUE THREAD

**Issue by wanglufei1** [bytedance/HLLM#29]
如下是训练结果路径，请问哪个是pytorch_model.bin模型呢？
[ma-user saved]$ll -R
.:
total `8`
drwxr-x--- 2 ma-user ma-group 4096 Dec 10 16:42 HLLM
drwxr-x--- 3 ma-user ma-group 4096 Dec 10 16:50 HLLM-0.pth

./HLLM:
total 80
-rw-r----- 1 ma-user ma-group 81411 Dec 10 16:51 Dec-10-2024_16-42-47.log

./HLLM-0.pth:
total 36
drwxr-x--- 2 ma-user ma-group  4096 Dec 10 16:49 checkpoint
-rw-r----- 1 ma-user ma-group    10 Dec 10 16:50 latest
-rwxr----- 1 ma-user ma-group 25314 Dec 10 16:50 zero_to_fp32.py

./HLLM-0.pth/checkpoint:
total 42211360
-rw-r----- 1 ma-user ma-group 18524614940 Dec 10 16:50 bf16_zero_pp_rank_0_mp_rank_00_optim_states.pt
-rw-r----- 1 ma-user ma-group 18524614940 Dec 10 16:50 bf16_zero_pp_rank_1_mp_rank_00_optim_states.pt
-rw-r----- 1 ma-user ma-group  6175182736 Dec 10 16:49 mp_rank_00_model_states.pt
[ma-user saved]$

**Comment by threestone965** [comment]
看一下zero_to_fp32.py文件，我用这个文件转换成功了

**Comment by wanglufei1** [comment]
> 看一下zero_to_fp32.py文件，我用这个文件转换成功了

 感谢回复
