### ISSUE TITLE
How to solve ```CUDA out of memory```?

### ISSUE THREAD

**Issue by mathetian** [bytedance/HLLM#3]
Hi, 

I'm using NVIDIA L20 (48GB) and when I execute ```sh reproduce/HLLM-Pixel.sh```, I get a ```CUDA out of memory```(like below) error. I tried reducing the train_batch_size from 8 to 2, but the error persists.

Can you please advise on how to handle this situation? By the way, I don't have access to A100/H800.

``` torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.20 GiB. GPU 0 has a total capacity of 44.53 GiB of which 2.56 GiB is free. Process 3810441 has 41.95 GiB memory ```

**Comment by ssyzeChen** [comment]
Could you please try to use gradient_checkpointing and deepspeed with zero3 to save gpu memory?
You can use them by `--gradient_checkpointing True` and `--stage 3`.
Hope these commands help you well.
