### ISSUE TITLE
how to use timestamp feature

### ISSUE THREAD

**Issue by threestone965** [bytedance/HLLM#31]
Thank you for your great work. 
Is the use of timestamp the same as the pseudo code in the appendix of the paper? 
The item embedding and timestamp embedding are added and then sent to the user model. 
I want to reproduce the experiment of integrating timestamp. 
Can you share your hyper-parameter settings for the timestamp ablation experiment?

**Comment by ssyzeChen** [comment]
Hi~ We use the same pseudo code on timestamp for ablation study, hyper-params are the same with other experiments.

**Comment by threestone965** [comment]
> Hi~ We use the same pseudo code on timestamp for ablation study, hyper-params are the same with other experiments.

can you share your train script?
