### ISSUE TITLE
请问报告结果是乘以100后展示的吗？我在自己的机器上重现后都是没有超过1的小数

### ISSUE THREAD

**Issue by wanglufei1** [bytedance/HLLM#32]
Method	Dataset	Negatives	R@10	R@50	R@200	N@10	N@50	N@200
HSTU	Pixel8M	5632	4.83	10.30	18.28	2.75	3.94	5.13
SASRec	Pixel8M	5632	5.08	10.62	18.64	2.92	4.12	5.32
HLLM-1B	Pixel8M	5632	6.13	12.48	21.18	3.54	4.92	6.22
HSTU-large	Books	512	5.00	11.29	20.13	2.78	4.14	5.47
SASRec	Books	512	5.35	11.91	21.02	2.98	4.40	5.76
HLLM-1B	Books	512	6.97	14.61	24.78	3.98	5.64	7.16
HSTU-large	Books	28672	6.50	12.22	19.93	4.04	5.28	6.44
HLLM-1B	Books	28672	9.28	17.34	27.22	5.65	7.41	8.89
HLLM-7B	Books	28672	9.39	17.65	27.59	5.69	7.50	8.99

**请问如上结果是乘以100后展现的报告吗？我在自己的机器上重现后都是没有超过1的小数，麻烦确认下哈，多谢啦！！！**

18 Dec 15:48    INFO  epoch 11 training [time: 152.95s, train loss: 6860.8033]
18 Dec 15:48    INFO  epoch 11 evaluating [time: 18.06s, valid_score: 0.060586]
18 Dec 15:48    INFO  valid result: 
recall@5 : 0.0380013    recall@10 : 0.0568976    recall@50 : 0.1264    recall@200 : 0.220224    ndcg@5 : 0.0253588    ndcg@10 : 0.0314342    ndcg@50 : 0.0465286    ndcg@200 : 0.0605861

**Comment by ssyzeChen** [comment]
Hi~ 是的，报告的结果为百分比
