### ISSUE TITLE
The implementation of "Discriminative Recommendation"

### ISSUE THREAD

**Issue by LeiShenVictoria** [bytedance/HLLM#7]
Hi, the code posted seems to be mainly for "Generative Recommendation" and only contains nce loss.
Are you going to post the code for the "Discriminative Recommendation" part?
Thanks a lot!

**Comment by ssyzeChen** [comment]
Hi. 
This code repo focuses on Generative Recommendation to maintain consistency with prior works. 
We apologize that the Discriminative Recommendation, mainly based on real industrial data, is not convenient to release at this time. In case we find a suitable public dataset, we will add this later.
